# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data]
highlighter:      pygments

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            Apple Pail
tagline:          'A central location for all things Apple'
description:      ''
url:              http://applepail.com
baseurl:          '/'
paginate:         3
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Author Info
author:
  name:           'Moderator'
  url:            http://applepail.com

# Social Integration
social:
  twitter:        applepailsite
  disqus:         applepail
  addthis_pubid:  ra-5592bd8c62b55206

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:      UA-64658979-1
  super_proxy_url:  

# Github
github:
  repo:           git@github.com:jagatfx/jagatfx.github.io.git
  feedback:       http://applepail.com/feedback

# Version Info
version:          0.0.0
